#!/usr/bin/env python
import re
import subprocess
import sys

f = open( sys.argv[1], "r" )
commit_msg = f.read();
f.close()

current_branches = subprocess.check_output(["git", "branch", "--no-color"])

# Valid branch name examples:
# feature/DEB-1234
# feature/text-DEB-1234
# release/DEB-1234
# release/text-DEB-1234
# hotfix/DEB-1234
# hotfix/text-DEB-1234
jiraid_match = re.search('\* (feature|release|uat|hotfix)/\w*-{0,1}(?P<jid>deb\-[0-9]{1,9})', current_branches, re.I)

if jiraid_match:
   jira_id = jiraid_match.group('jid')
   f = open(sys.argv[1], "a")
   f.write(jira_id.upper())
   f.close()

sys.exit(0)
